# Generated by Django 5.1.6 on 2025-03-27 14:24

import videoflix_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[videoflix_app.models.validate_thumbnail]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[videoflix_app.models.validate_video_file]),
        ),
    ]
