# Generated by Django 5.1.6 on 2025-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='genres',
        ),
        migrations.AddField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(related_name='video', to='videoflix_app.genre'),
        ),
    ]
