# Generated by Django 5.1.6 on 2025-03-27 17:58

from django.db import migrations


def create_genres(apps, schema_editor):
    Genre = apps.get_model('videoflix_app', 'Genre')
    genres_list = ['Action', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Historical', 'Horror', 'Romance', 'Science fiction', 'Thriller']
    for genre in genres_list:
        Genre.objects.create(name=genre)


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_genre_remove_video_genres_video_genres'),
    ]

    operations = [
        migrations.RunPython(create_genres),
    ]
